name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install build-essential
      run: sudo apt-get update && sudo apt-get install -y build-essential && sudo apt install -y libsdl2-2.0-0 libsdl2-gfx-1.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-net-2.0-0 libsdl2-ttf-2.0-0 libsdl2-dev libsdl2-ttf-dev

    - name: Create Makefile
      run: ./CMakeGCC.sh

    - name: Compile
      run: cd ./bin/make && make && cd ../..

    - name: Run Program
      run: ./bin/make/Release/sobel

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create cmake
      run: ./CMakeVS2013.bat

    - name: Build
      run: |
        cmake -B build
        cmake --build build --config Release
        
    - name: Run Program
      run: Start-Process -FilePath "D:\a\sobel_morpho\sobel_morpho\build\Release\sobel.exe"
      
